[package]
name = "echo"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { git = "https://github.com/risc0/risc0", rev = "17ed98c3243258ad912fd52a289fef6725f17c90", default-features = false, features = ["std"] }

[profile.release]
debug = 1
lto = "thin"
